#!/usr/bin/env bash
# generate-reports.sh — assemble the committed PII-free markdown report bundle.
#
# Runs the 4 reports/*.sql over the Parquet snapshot via DuckDB (markdown render) and
# assembles a single dated markdown bundle. Once the Parquet exists this needs NO MariaDB
# and NO 6.8 GiB archive — fully decoupled.
#
# Aborts if either Parquet is missing (no silent empty reports) or any report errors.
#
# Determinism (SCEN-007): the report SQL is deterministic (explicit ORDER BY, stable
# tie-breaks, no clock/random). The ONLY non-deterministic line in the bundle is the single
# run-date header line, set from REPORT_DATE (NOT `date`) so even that is reproducible when
# pinned. The SCEN-007 diff excludes that one header line.
#
# Env / args (env wins; defaults shown):
#   OUT_DIR      Parquet snapshot dir   default <script_dir>/dataset
#   BUNDLE       output markdown path
#                default docs/data-ops/2026-06-09-issue-45-phase35-dataset/reports/log-veh-reports-2026-06-09.md
#   REPORT_DATE  the run-date header string (do NOT shell out to `date` for determinism)
#                default 2026-06-09
#   DUCKDB       duckdb binary           default duckdb on PATH (or ~/.local/bin/duckdb)
#
# On success: prints the bundle path; exits 0.
set -Eeuo pipefail
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/dataset}"
BUNDLE="${BUNDLE:-$REPO_ROOT/docs/data-ops/2026-06-09-issue-45-phase35-dataset/reports/log-veh-reports-2026-06-09.md}"
REPORT_DATE="${REPORT_DATE:-2026-06-09}"

DUCKDB="${DUCKDB:-}"
if [[ -z "$DUCKDB" ]]; then
  if command -v duckdb >/dev/null 2>&1; then DUCKDB="duckdb"
  elif [[ -x "$HOME/.local/bin/duckdb" ]]; then DUCKDB="$HOME/.local/bin/duckdb"
  else DUCKDB="duckdb"; fi
fi

log() { printf '[reports] %s\n' "$*" >&2; }
die() { printf '[reports][ERROR] %s\n' "$*" >&2; exit 1; }

command -v "$DUCKDB" >/dev/null 2>&1 || [[ -x "$DUCKDB" ]] || die "duckdb not found: $DUCKDB"

SEARCH_PARQUET="$OUT_DIR/search_flat.parquet"
CAT_PARQUET="$OUT_DIR/cat_quotes.parquet"
[[ -f "$SEARCH_PARQUET" ]] || die "missing Parquet: $SEARCH_PARQUET — run export-dataset.sh first"
[[ -f "$CAT_PARQUET" ]]    || die "missing Parquet: $CAT_PARQUET — run export-dataset.sh first"

# The 4 report files, in order, with human titles for the section headings.
declare -a REPORT_FILES=(
  "$SCRIPT_DIR/reports/01-demand-by-branch-month.sql"
  "$SCRIPT_DIR/reports/02-pricing-by-category-season.sql"
  "$SCRIPT_DIR/reports/03-quote-failure-rate.sql"
  "$SCRIPT_DIR/reports/04-availability-and-behavior.sql"
)
declare -a REPORT_TITLES=(
  "Report 01 — Demand by branch + month + routes"
  "Report 02 — Pricing by category + season (the price corpus)"
  "Report 03 — Quote failure rate"
  "Report 04 — Availability + booking behavior"
)
for f in "${REPORT_FILES[@]}"; do
  [[ -f "$f" ]] || die "report SQL not found: $f"
done

mkdir -p "$(dirname "$BUNDLE")"
tmp_bundle="$(mktemp /tmp/log-veh-bundle.XXXXXX.md)"
report_err="$(mktemp /tmp/log-veh-report.XXXXXX.err)"

# --- Header (the run-date line is the only non-deterministic content) ----------
{
  printf '# log_veh Phase 3.5 — formal reports (issue #45)\n\n'
  printf '<!-- RUN-DATE: %s -->\n\n' "$REPORT_DATE"
  printf 'PII-free aggregate reports over the `log_veh` Parquet snapshot '
  printf '(`search_flat` 664,126 rows + `cat_quotes` 2,974,126 rows). '
  printf 'Generated by `generate-reports.sh` over the gitignored Parquet; '
  printf 'reproducible (deterministic ORDER BY, no clock/random in the queries).\n\n'
  printf 'Denominators: demand/behavior reconcile to all rows = `rp_kind='\''valid'\''` = '
  printf '**664,126**; quote-failure error subset = **184,724**; availability denominator '
  printf '`pd_kind='\''array'\''` = **479,402**; pricing is a quantile report '
  printf '(per-category `n_quotes` sum to **2,974,126**).\n\n'
  printf -- '---\n\n'
} > "$tmp_bundle"

# --- Render each report as a markdown section ----------------------------------
for i in "${!REPORT_FILES[@]}"; do
  f="${REPORT_FILES[$i]}"
  title="${REPORT_TITLES[$i]}"
  log "rendering: $f"
  printf '## %s\n\n' "$title" >> "$tmp_bundle"
  # DuckDB -markdown renders every result set as a markdown table. SET VARIABLE via -c
  # runs before -f so the report's coalesce keeps OUR dataset_dir. Abort on any SQL error.
  if ! "$DUCKDB" -markdown \
        -c "SET VARIABLE dataset_dir = '$OUT_DIR'" \
        -f "$f" >> "$tmp_bundle" 2>"$report_err"; then
    sed 's/^/[reports][duckdb-stderr] /' "$report_err" >&2 || true
    find "$report_err" "$tmp_bundle" -type f -delete 2>/dev/null || true
    die "report failed: $f — the existing bundle (if any) was left UNCHANGED, not overwritten"
  fi
  printf '\n' >> "$tmp_bundle"
done
find "$report_err" -type f -delete 2>/dev/null || true

# --- Publish the bundle --------------------------------------------------------
cat "$tmp_bundle" > "$BUNDLE"
find "$tmp_bundle" -type f -delete 2>/dev/null || true

log "bundle written: $BUNDLE"
printf '%s\n' "$BUNDLE"
